-- DATE & TIME & DATETIME -- 
USE learn_db;

CREATE TABLE dt(
	jd DATE,
    jt TIME,
    jdt DATETIME
);
    
INSERT INTO dt
VALUES ('2022-04-17','23:00:00', '2023-05-16 22:05:02');


-- DATE TIME FUNCTIONS

-- CURDATE, CURTIME(), NOW() --
INSERT INTO dt
VALUES (CURDATE(),CURTIME(),NOW());

-- DAYNAME -- 
SELECT DAYNAME(CURDATE());

-- DAYOFMONTH --
SELECT DAYOFMONTH(CURDATE());

-- DAYOFWEEK --
SELECT DAYOFWEEK(CURDATE());

-- MONTHNAME --
SELECT MONTHNAME(CURDATE());

-- YEARNAME --
SELECT YEAR(CURDATE());

-- DAYNAME --
SELECT DAYNAME(CURDATE());


-- HOUR -- 
SELECT HOUR(CURTIME());

-- MINTUE --
SELECT MINUTE(CURTIME());


-- DATE FORMATTING --
SELECT DATE_FORMAT(NOW(), '%D %a at %T');
SELECT DATE_FORMAT(NOW(), '%m/%d/%y');

-- DATE MATH --

-- DATEDIFF -- 
SELECT DATEDIFF(NOW(),'2000-11-05');

-- DATE_ADD --
SELECT DATE_ADD(NOW(),INTERVAL 1 DAY);
SELECT DATE_ADD(NOW(),INTERVAL 1 MONTH);
SELECT DATE_ADD(NOW(),INTERVAL 1 YEAR);

-- DATE_SUB 
SELECT DATE_SUB(NOW(),INTERVAL 1 DAY);
SELECT DATE_SUB(NOW(),INTERVAL 1 MONTH);
SELECT DATE_SUB(NOW(),INTERVAL 1 YEAR);

-- TIMEDIFF
SELECT TIMEDIFF(CURTIME(),'16:00:00');

